# Generated by Django 5.2.7 on 2025-10-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSM_User_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITSM.itsm_role_model')),
            ],
        ),
        migrations.CreateModel(
            name='ITSM_Group_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('membros', models.ManyToManyField(to='ITSM.itsm_user_model')),
            ],
        ),
    ]
