# Generated by Django 5.2.7 on 2025-11-23 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSM', '0002_itsm_user_model_itsm_group_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itsm_group_model',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='itsm_role_model',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='itsm_user_model',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='itsm_ticket_model',
            name='status',
            field=models.CharField(choices=[('Open', 'Aberto'), ('In Progress', 'Em Progresso'), ('Resolved', 'Resolvido'), ('Closed', 'Fechado')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='itsm_user_model',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ITSM.itsm_role_model'),
        ),
    ]
