# Generated by Django 5.2.7 on 2025-11-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSM', '0003_rename_nome_itsm_group_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm_user_model',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itsm_user_model',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
