# Generated by Django 5.2.7 on 2025-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSM', '0004_itsm_user_model_first_name_itsm_user_model_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsm_role_model',
            name='name_ger',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
