# Generated by Django 5.2.7 on 2025-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSM', '0005_itsm_role_model_name_ger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsm_role_model',
            name='name_ger',
        ),
        migrations.AddField(
            model_name='itsm_role_model',
            name='name_ger',
            field=models.ManyToManyField(blank=True, to='ITSM.itsm_group_model'),
        ),
    ]
