# Generated by Django 5.2.7 on 2025-11-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSM', '0006_remove_itsm_role_model_name_ger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsm_role_model',
            name='name_ger',
        ),
        migrations.AddField(
            model_name='itsm_role_model',
            name='name_ger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ITSM.itsm_user_model'),
        ),
    ]
